[tool.poetry]
name = "sherlock"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
seaborn = "^0.11.1"
matplotlib = "^3.4.2"
Theano = "^1.0.5"
pymc3 = "^3.11.2"
scikit-learn = "^0.22.0"
numpy = ">=1.19.2,<1.20.0"
pygmo = "^2.16.1"
scipy = "^1.7.0"
dcor = "^0.5.3"
GPy = "^1.10.0"
gpflow = "^2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^5.5.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
